/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package board_proj;

public class TestMain{
	public static void main(String[] args) throws ClassNotFoundException, InstantiationException, IllegalAccessException {
		
		// 흔하지 않은 생성 법
		//1. 클래스 이름 정의
		//* Class<?> => 제네릭 물음표는, 왜쓰냐? 타입에 따라 각각 다들 다르니까 물음표를 써주는거다.
		//2.
		String className = "board_proj.Sum"; 
		
		Class<?> cls = Class.forName(className);
		
		Sum s = (Sum) cls.newInstance();
		s.add(5, 10);
		
		Sum s2 = new Sum();
		s2.add(10, 2);
	}
}
//commandAction.properties